package Estruturas;

public enum TokenID {
    ADDSUB_OP, RELA_OP, ARITH_OP, BITWISE_OP, NOT_OP, WHILE, IF,
    ELSE, ASSIGN, ASPA, LPAR, RPAR, VIRG, PVIRG, LCHAVETA, RCHAVETA,
    FUNCTION, MODULE, SIZE, ID, STRING, INTEGER, PONTO, LPARR, RPARR, ERROR
}
